#!/bin/bash

set -eu

function usage() {
  echo -n \
"Usage: $(basename "$0") macos|linux
Build and switch to a new home manager generation
"
}

function build_linux() {
  nix build --impure .#homeConfigurations.linux.activationPackage
}

function build_macos() {
  nix build --impure .#homeConfigurations.macOS.activationPackage
}

function activate_home() {
  nix develop nixpkgs#bash --command ./result/activate
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  if [ "${1:-}" = "--help" ]; then
    usage
  else
    case "${1}" in
      linux) build_linux;;
      macos) build_macos;;
    esac

    activate_home
  fi
fi

