#!/usr/bin/env bash

set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0")
Run tests.
"
}

function build_home() {
    ./scripts/switch "${1}"
}

function check_formatting() {
    nixpkgs-fmt --check *.nix
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Building home derivation"
        lowercasedArg=$(tr '[:upper:]' '[:lower:]' <<< "${1}")
        build_home "${lowercasedArg}"

        echo "Verifying all nix files follow formatting conventions"
        check_formatting
    fi
fi


