name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_SECRET_KEY }}
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: jisantuc
    - run: ./scripts/test ${{ runner.os }}-x86
      env:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
